### ISSUE TITLE
Does not build with rust 1.80.0

### ISSUE THREAD

**Issue by pbsds** [CloudCannon/pagefind#678]
While building pagefind_ui i get
```
pagefind> error[E0282]: type annotations needed for `Box<_>`
pagefind>   --> /build/pagefind-1.1.0-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
pagefind>    |
pagefind> 83 |     let items = format_items
pagefind>    |         ^^^^^
pagefind> ...
pagefind> 86 |     Ok(items.into())
pagefind>    |              ---- type must be known at this point
pagefind>    |
pagefind> help: consider giving `items` an explicit type, where the placeholders `_` are specified
pagefind>    |
pagefind> 83 |     let items: Box<_> = format_items
pagefind>    |              ++++++++
pagefind> 
```

Likely caused by the unfixable regression https://github.com/rust-lang/rust/issues/127343 as reported by @\allysais in https://github.com/NixOS/nixpkgs/issues/332957, who notes that:

>  Most commonly, the required fix is just to update the "time" crate.

**Comment by pbsds** [comment]
This seems to be the issue that has brought down your CI

![image](https://github.com/user-attachments/assets/3e67da58-d210-4247-bd8d-8f6360b946b9)

Link to a run: https://github.com/CloudCannon/pagefind/actions/runs/9752597405/job/26916380265?pr=653

**Comment by bglw** [comment]
Thanks @pbsds ! I've been fixing this on some other crates and hadn't made it to pagefind yet 😅 Will merge your PR shortly ❤️
